name: Issue Status Automation

# This workflow handles automatic project status updates for issues:
# 1. When Claude bot starts work -> sets status to "In Progress" and assigns to codekiln
# 2. When an issue is closed -> sets status to "Done"

on:
  issue_comment:
    types: [created]
  issues:
    types: [closed]

jobs:
  update-status-on-claude-trigger:
    name: Update status when Claude starts work
    if: |
      github.event_name == 'issue_comment' &&
      github.actor == 'codekiln' &&
      contains(github.event.comment.body, '@claude')
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Assign issue and update status to In Progress
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          chmod +x .github/scripts/update-issue-status.sh
          .github/scripts/update-issue-status.sh "${{ github.event.issue.number }}" "in_progress" "codekiln"

  update-status-on-close:
    name: Update status when issue closed
    if: github.event_name == 'issues' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Update status to Done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          chmod +x .github/scripts/update-issue-status.sh
          .github/scripts/update-issue-status.sh "${{ github.event.issue.number }}" "done"
